name: CI Pipeline (PR to Develop Branch)

on:
  pull_request:
    branches:
      - develop

jobs:
  call-template:
    uses: ecommerce-microservice-backend-app-actions/ci-pipelines/.github/workflows/pr-dev.yml@main
    with:
      projectKeyBase: ${{ github.repository }}
      projectNameBase: ${{ github.repository }}
