name: CI Pipeline (PR to Develop Branch)

on:
  pull_request:
    branches:
      - develop

jobs:
  call-template:
    uses: ecommerce-app-devops/ci-pipelines/.github/workflows/pr-dev.yaml@main
    with:
      projectKeyBase: ${{ github.repository }}
      projectNameBase: ${{ github.repository }}
